config:
  elk:
    es:
      host:  10.1.6.155
      port:   9300
      clusterName: uuzz-cluster



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze60e5hwg306yw8ho.mysql.rds.aliyuncs.com/lottery_jkc
    username: lottery_jkc
    password: Lottery-2016