spring:
  profiles:
    active:  'develop'


server:
  port: 7001

alicp:
  log:
    appName:


management:
  port: 7002


multipart:
  maxFileSize: 5Mb


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true


