config:
  elk:
    es:
      host:   127.0.0.1
      port:   9300
      clusterName: my-application
log:
  agent:
    bizName: "xingyunsaiche"
    appName: "hunan-lottery"
    ips: "127.0.0.1"
    logPathConfigList:
      inputPath: "/Users/chengjing/Downloads/HNLRG_sample_logs/app01/test.log"
      fileName:   "test.log"
      pattern: ""
      outPutName: "test.json.out"
