# spring相关配置
spring:
  profiles:
    active:  'dev'
  tddl:
      app: 'ALICPPRIZE_APP'
  # 数据源配置
#  datasource:
#    url: 'jdbc:mysql://rm-2ze60e5hwg306yw8ho.mysql.rds.aliyuncs.com/lottery_jkc'
#    username: 'lottery_jkc'
#    password: 'Lottery-2016'
#    'driver-class-name': 'com.mysql.jdbc.Driver'
  # velocity 配置
  velocity:
    charset: 'UTF-8'
    resourceLoaderPath: 'classpath:/templates/'
    suffix: '.html'
    properties:
      input:
        encoding: 'UTF-8'
      output:
        encoding: 'UTF-8'      

# 容器配置
#server:
  # https 配置
#  ssl:
#    enabled: true
#    'keyStore': '/Users/Adison/.keystore'
#    'keyStorePassword': '123456'
#    'keyStoreType': 'JKS'
#    'keyAlias': 'alicpjkc2'
#    'keyPassword': '123456'
# mybatis 配置
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true # 列名与属性名称按照驼峰格式自动匹配

server:
  port: 6011






